version: "3.7"
services:

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: db
      POSTGRES_USER: app
    volumes:
      - ./data:/var/lib/postgresql/data